version: '3.2'

networks:
      kr_network:
        driver: bridge
        ipam:
          driver: default
          config:
          -
            subnet: 192.168.10.0/24
             
volumes:   
      kr_datavolume:
      kr_dbvolume:
      
